//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Departments
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Departments()
    {
        this.EmployeesDetails = new HashSet<EmployeesDetails>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public string Location { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<EmployeesDetails> EmployeesDetails { get; set; }
}

public partial class Employees
{
    public int Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Gender { get; set; }

    public virtual EmployeesDetails EmployeesDetails { get; set; }
}

public partial class EmployeesDetails
{
    public int Id { get; set; }
    public int Salary { get; set; }
    public int DepartmentId { get; set; }
    public string JobTitle { get; set; }

    public virtual Departments Departments { get; set; }
    public virtual Employees Employees { get; set; }
}
